const CACHE_NAME = "multi-trip-v10.10.8-livecams-hokkaido-hakuba47-20261004";
const DEFAULT_TRIP = "shirakawago-shinhotaka-2027";
const SHELL_FILES = [
"./","./index.html","./live.html","./itinerary.html","./trip-info.html","./attractions.html","./manifest.webmanifest",
"./assets/multi-trip-context-v1.js","./assets/multi-trip-data-v1.js","./assets/multi-trip-nav-v1.js","./assets/multi-trip-itinerary-renderer-v1.js","./assets/multi-trip-attractions-renderer-v1.js","./assets/multi-trip-live-renderer-v1.js","./assets/multi-trip-live-entry-v1.js","./assets/multi-trip-weather-v1.js","./assets/multi-trip-shared-ui-v1.css","./assets/weather-profile-standard-v1.js","./assets/multi-trip-mode-core-v1.js","./assets/multi-trip-today-mode-v1.js","./assets/multi-trip-driving-mode-v1.js","./assets/multi-trip-mode-weather-bridge-v1.js","./assets/multi-trip-generic-qa-fix-v1.js","./assets/multi-trip-departure-checklist-v1.js","./assets/multi-trip-checklist-sync-v1.js","./assets/itinerary-hotel-detail-v1.js","./assets/multi-trip-trip-info-renderer-v1.js","./assets/info-icon-repair-v1.js",
"./assets/attraction-info.css","./assets/attraction-info.js","./assets/attractions-catalog.js","./assets/attractions-layout-v2.js","./assets/attractions-group-fix.js","./assets/catalog-link.js","./assets/nav-enhancements-v1.js","./assets/i18n-v1.js","./assets/i18n-content-en-v1.js","./assets/i18n-polish-en-v1.js","./assets/travel-mode-v1.js","./assets/travel-mode-nav-fix-v1.js","./assets/driving-mode-v1.js","./assets/live-v9-1-sync.js","./assets/live-v9-2-sync.js","./assets/trip-core-v1.js","./assets/weather-suitability-v1.js","./assets/d6-d8-weather-decision-v1.js","./assets/trip-no-observers-v2.js","./assets/trip-v9-1-routing.js","./assets/trip-v9-1-visit-fix.js","./assets/version-v901-fix.js","./assets/site-shell-v7.css","./assets/site-shell-v7.js","./assets/trip-v8.css","./assets/trip-v8-1.css","./assets/trip-v8-data.js","./assets/trip-v8-1-overrides.js","./assets/trip-v8-ui.js","./assets/trip-enhancement-data.js","./assets/trip-user-overrides.js","./assets/trip-v8-7-user-plan.js","./assets/trip-v8-8-d2-plan.js","./assets/trip-v8-9-user-fixes.js","./assets/trip-v9-final-fixes.js","./assets/trip-v9-hotfix.js","./assets/checklist-sync.js","./assets/trip-enhancements-v2.css","./assets/trip-enhancements-v3.css","./assets/trip-deep-info-d1-d4.js","./assets/trip-deep-info-d5-d9.js","./assets/trip-deep-info-backups.js","./assets/trip-enhancements-v3.js",
"./assets/images/d1-matsumoto-castle.jpg","./assets/images/d1-shinano.jpg","./assets/images/d1-centrair.jpg","./assets/images/d2-shiraito.jpg","./assets/images/d2-onioshidashi.jpg","./assets/images/d2-karuizawa-outlet.jpg","./assets/images/d3-obuse.jpg","./assets/images/d3-shibu-onsen.jpg","./assets/images/d3-shibu-onsen-day.jpg","./assets/images/d4-aeon-suzaka.jpg","./assets/images/d4-monkey-trail.jpg","./assets/images/d4-snow-monkey.jpg","./assets/images/d5-hakuba-iwatake.jpg","./assets/images/d5-mountain-harbor.jpg","./assets/images/d5-white-park.jpg","./assets/images/d6-shinhotaka.jpg","./assets/images/d6-takayama.jpg","./assets/images/d6-hida-cave.jpg","./assets/images/d7-shirakawago.jpg","./assets/images/d7-shirakawago-view.jpg","./assets/images/d8-daio-wasabi.jpg","./assets/images/d9-aeon-matsumoto.jpg","./assets/images/d9-matsumoto-station.jpg"
];
async function fetchAndCache(cache,path){try{const r=await fetch(path,{cache:'no-store'});if(r&&r.ok){await cache.put(path,r.clone());return r;}return null;}catch(e){return null;}}
async function precacheTrips(cache){
  const regResp=await fetchAndCache(cache,'./trips/registry.json');
  if(!regResp)return;
  let registry;try{registry=await regResp.clone().json();}catch(e){return;}
  const trips=(registry.trips||[]).filter(t=>t&&t.id&&t.status!=='hidden');
  await Promise.allSettled(trips.map(async t=>{
    const id=String(t.id),configPath=t.config||('trips/'+encodeURIComponent(id)+'/trip.json');
    const configResp=await fetchAndCache(cache,configPath);if(!configResp)return;
    let cfg={};try{cfg=await configResp.clone().json();}catch(e){}
    const base='trips/'+encodeURIComponent(id)+'/',defaults={itinerary:'itinerary.json',tripInfo:'trip-info.json',hotels:'hotels.json',attractions:'attractions.json',liveCams:'live-cams.json',weather:'weather.json'};
    const files=Object.assign({},defaults,cfg.dataFiles||{});
    await Promise.allSettled(Object.values(files).filter(Boolean).map(file=>fetchAndCache(cache,base+file)));
    const assets=cfg.assets||{};
    await Promise.allSettled(Object.values(assets).filter(v=>typeof v==='string'&&!/^https?:\/\//i.test(v)).map(path=>fetchAndCache(cache,path)));
  }));
}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);await cache.addAll(SHELL_FILES);await precacheTrips(cache);})());self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE_NAME).map(key=>caches.delete(key)))));self.clients.claim();});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting();});
async function patchLiveDocument(response,url){if(!response||!url.pathname.endsWith('/live.html'))return response;try{let text=await response.text();const requested=url.searchParams.get('trip')||DEFAULT_TRIP,inject=[];if(!text.includes('assets/multi-trip-live-entry-v1.js'))inject.push('<script src="assets/multi-trip-live-entry-v1.js?v=2"><\/script>');if(requested===DEFAULT_TRIP&&!text.includes('assets/live-v9-2-sync.js'))inject.push('<script src="assets/live-v9-2-sync.js?v=8"><\/script>');if(inject.length)text=text.replace(/<\/body>/i,inject.join('\n')+'\n</body>');const headers=new Headers(response.headers);headers.delete('content-length');headers.delete('content-encoding');return new Response(text,{status:response.status,statusText:response.statusText,headers});}catch(e){return response;}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith('/version.json')){event.respondWith(fetch(request,{cache:'no-store'}).catch(()=>new Response(JSON.stringify({version:null,offline:true}),{headers:{'Content-Type':'application/json'}})));return;}if(/\/trips\/.*\.json$/.test(url.pathname)||url.pathname.endsWith('/trips/registry.json')){event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{if(response&&response.status===200){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));}return response;}).catch(()=>caches.match(request,{ignoreSearch:true})));return;}if(request.mode==='navigate'||request.destination==='document'){event.respondWith((async()=>{try{const response=await fetch(request,{cache:'no-store'}),delivered=await patchLiveDocument(response,url),copy=delivered.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));return delivered;}catch(e){const cached=await caches.match(request);if(cached)return patchLiveDocument(cached,url);return caches.match('./itinerary.html');}})());return;}if(request.destination==='script'||request.destination==='style'||/\.(?:js|css)$/.test(url.pathname)){event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{if(response&&response.status===200){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));}return response;}).catch(()=>caches.match(request,{ignoreSearch:true})));return;}event.respondWith(caches.match(request,{ignoreSearch:true}).then(cached=>cached||fetch(request).then(response=>{if(!response||response.status!==200)return response;const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));return response;})));});
